server.port: 8084

security:
  basic:
    enabled: false
    
spring.oauth2:
  client:
    accessTokenUri: ${targets.uaa}/oauth/token
    userAuthorizationUri: ${targets.uaa}/oauth/authorize
    clientId: admin-portal
    clientSecret: secret
    scope: openid,menu.read,menu.write,order.admin
  resource:
    jwt.keyUri: ${targets.uaa}/token_key

